import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'
import { verifyViewerCookie } from '@/lib/viewer-auth'

const PASSWORD = process.env.AUTH_PASSWORD ?? ''
const VIEWER_SECRET = process.env.VIEWER_COOKIE_SECRET ?? ''

async function sha256Hex(input: string): Promise<string> {
  const data = new TextEncoder().encode(input)
  const buf = await crypto.subtle.digest('SHA-256', data)
  return Array.from(new Uint8Array(buf)).map(b => b.toString(16).padStart(2, '0')).join('')
}

let authHashPromise: Promise<string> | null = null
function getAuthHash() {
  if (!authHashPromise) authHashPromise = sha256Hex(PASSWORD)
  return authHashPromise
}

// Routes a viewer cookie can reach. Anything else stays operator-only.
function isViewerPath(pathname: string): boolean {
  // /thepark hub is paid-member territory, but /thepark/operator is admin-only.
  if (pathname.startsWith('/thepark/operator')) return false
  if (pathname === '/thepark' || pathname.startsWith('/thepark/')) return true
  return (
    pathname === '/theyield' ||
    pathname.startsWith('/theyield/') ||
    pathname === '/help' ||
    pathname === '/handicappers' ||
    pathname.startsWith('/handicappers/') ||
    pathname === '/viewer' ||
    pathname.startsWith('/viewer/') ||
    pathname === '/marketplace' ||
    pathname.startsWith('/marketplace/') ||
    pathname === '/bazaar' ||
    pathname.startsWith('/bazaar/') ||
    pathname === '/api/viewer/edges' ||
    pathname === '/api/viewer/scoreboard' ||
    pathname === '/api/viewer/articles' ||
    pathname === '/api/viewer/wallet' ||
    pathname === '/api/viewer/dms' ||
    pathname.startsWith('/api/marketplace/') ||
    // Viewer-scoped Bazaar API routes. The HMAC-only bot endpoints
    // (events/*, milestones/submit, escrow/release, disputes, ledger)
    // are listed in the always-public block below; they reject any
    // request lacking a valid X-Bazaar-Sig header.
    pathname === '/api/bazaar/skills' ||
    pathname === '/api/bazaar/gigs' ||
    pathname.startsWith('/api/bazaar/gigs/') ||
    pathname === '/api/bazaar/wallet' ||
    pathname === '/api/bazaar/wallet/link' ||
    pathname === '/api/bazaar/bridge' ||
    pathname === '/api/bazaar/escrow/init' ||
    pathname === '/api/viewer/login' // POST allowed; GET is harmless
  )
}

// Legacy /local/* paths — moved out from under /local. Redirect to preserve
// bookmarks. Issued before auth so the redirect works for everyone.
const LOCAL_REDIRECTS: Record<string, string> = {
  '/local':                       '/',
  '/local/sports':                '/theyield/edges',
  '/local/commodities':           '/theyield/commodities',
  '/local/theyield':              '/theyield',
  '/local/theyield/sports':       '/theyield/sports',
  '/local/theyield/commodities':  '/theyield/commodities',
}

export async function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl

  // /lila moved to /thepark/operator. Preserve old bookmarks.
  if (pathname === '/lila' || pathname.startsWith('/lila/')) {
    const tail = pathname.slice('/lila'.length)
    return NextResponse.redirect(new URL(`/thepark/operator${tail}`, request.url))
  }

  // /local/* paths are gone. Bounce to the new homes before auth checks.
  const localRedirect = LOCAL_REDIRECTS[pathname]
  if (localRedirect) {
    return NextResponse.redirect(new URL(localRedirect, request.url))
  }

  // Public / always-allowed paths.
  if (
    pathname === '/' ||
    pathname.startsWith('/bounty') ||
    pathname.startsWith('/commodities') ||
    pathname.startsWith('/sports') ||
    pathname.startsWith('/subscribe') ||
    pathname.startsWith('/login') ||
    pathname.startsWith('/api/login') ||
    pathname.startsWith('/api/health') ||
    pathname.startsWith('/api/public/') ||
    // Gumroad webhook is gated by GUMROAD_WEBHOOK_SECRET in the URL.
    pathname.startsWith('/api/gumroad/webhook') ||
    // Bot-only Bazaar endpoints — gated by X-Bazaar-Sig HMAC at the route.
    pathname.startsWith('/api/bazaar/events/') ||
    pathname === '/api/bazaar/milestones/submit' ||
    pathname === '/api/bazaar/escrow/release' ||
    pathname === '/api/bazaar/disputes' ||
    pathname === '/api/bazaar/ledger' ||
    pathname === '/api/bazaar/rooms/negotiation' ||
    // Viewer login is the only way an unauthenticated viewer can hit the
    // server (to redeem their license key). Always allow POST through.
    pathname === '/api/viewer/login' ||
    pathname === '/api/me' ||
    pathname.startsWith('/specs') ||
    pathname.startsWith('/_next') ||
    // OG / Twitter cards generated by next/og — must be reachable
    // without auth so social crawlers can fetch the image.
    pathname.startsWith('/opengraph-image') ||
    pathname.startsWith('/twitter-image') ||
    pathname === '/manifest.json' ||
    pathname === '/sw.js' ||
    pathname.startsWith('/icon-')
  ) {
    return NextResponse.next()
  }

  // Fail closed: if no password is configured, nobody gets in.
  if (!PASSWORD) {
    return NextResponse.redirect(new URL('/login', request.url))
  }

  // Operator cookie passes everything.
  const operatorCookie = request.cookies.get('lila_auth')
  const authHash = await getAuthHash()
  if (operatorCookie?.value === authHash) {
    return NextResponse.next()
  }

  // Viewer cookie passes the viewer-allowed paths only.
  if (isViewerPath(pathname) && VIEWER_SECRET) {
    const viewerCookie = request.cookies.get('lila_viewer')
    const payload = await verifyViewerCookie(viewerCookie?.value, VIEWER_SECRET)
    if (payload) return NextResponse.next()
  }

  return NextResponse.redirect(new URL('/login', request.url))
}

export const config = {
  matcher: ['/((?!_next/static|_next/image|favicon\\.ico).*)'],
}
