import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'
import { verifyViewerCookie } from '@/lib/viewer-auth'

const PASSWORD = process.env.AUTH_PASSWORD ?? ''
const VIEWER_SECRET = process.env.VIEWER_COOKIE_SECRET ?? ''

async function sha256Hex(input: string): Promise<string> {
  const data = new TextEncoder().encode(input)
  const buf = await crypto.subtle.digest('SHA-256', data)
  return Array.from(new Uint8Array(buf)).map(b => b.toString(16).padStart(2, '0')).join('')
}

let authHashPromise: Promise<string> | null = null
function getAuthHash() {
  if (!authHashPromise) authHashPromise = sha256Hex(PASSWORD)
  return authHashPromise
}

// Routes a viewer cookie can reach. Anything else stays operator-only.
function isViewerPath(pathname: string): boolean {
  // /thepark hub is paid-member territory, but /thepark/operator is admin-only.
  if (pathname.startsWith('/thepark/operator')) return false
  if (pathname === '/thepark' || pathname.startsWith('/thepark/')) return true
  return (
    pathname === '/viewer' ||
    pathname.startsWith('/viewer/') ||
    pathname === '/marketplace' ||
    pathname.startsWith('/marketplace/') ||
    pathname === '/api/viewer/edges' ||
    pathname === '/api/viewer/articles' ||
    pathname === '/api/viewer/wallet' ||
    pathname === '/api/viewer/dms' ||
    pathname.startsWith('/api/marketplace/') ||
    pathname === '/api/viewer/login' // POST allowed; GET is harmless
  )
}

export async function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl

  // /lila moved to /thepark/operator. Preserve old bookmarks.
  if (pathname === '/lila' || pathname.startsWith('/lila/')) {
    const tail = pathname.slice('/lila'.length)
    return NextResponse.redirect(new URL(`/thepark/operator${tail}`, request.url))
  }

  // Public / always-allowed paths.
  if (
    pathname === '/' ||
    pathname.startsWith('/bounty') ||
    pathname.startsWith('/commodities') ||
    pathname.startsWith('/sports') ||
    pathname.startsWith('/subscribe') ||
    pathname.startsWith('/login') ||
    pathname.startsWith('/api/login') ||
    pathname.startsWith('/api/health') ||
    pathname.startsWith('/api/public/') ||
    // Telegram inbound webhook — Telegram's servers can't log in. The route
    // itself is gated on TELEGRAM_WEBHOOK_SECRET + owner chat_id.
    pathname.startsWith('/api/telegram/webhook') ||
    // Gumroad webhook is gated by GUMROAD_WEBHOOK_SECRET in the URL.
    pathname.startsWith('/api/gumroad/webhook') ||
    // Viewer login is the only way an unauthenticated viewer can hit the
    // server (to redeem their license key). Always allow POST through.
    pathname === '/api/viewer/login' ||
    pathname.startsWith('/specs') ||
    pathname.startsWith('/_next') ||
    // OG / Twitter cards generated by next/og — must be reachable
    // without auth so social crawlers can fetch the image.
    pathname.startsWith('/opengraph-image') ||
    pathname.startsWith('/twitter-image') ||
    pathname === '/manifest.json' ||
    pathname === '/sw.js' ||
    pathname.startsWith('/icon-')
  ) {
    return NextResponse.next()
  }

  // Fail closed: if no password is configured, nobody gets in.
  if (!PASSWORD) {
    return NextResponse.redirect(new URL('/login', request.url))
  }

  // Operator cookie passes everything.
  const operatorCookie = request.cookies.get('lila_auth')
  const authHash = await getAuthHash()
  if (operatorCookie?.value === authHash) {
    return NextResponse.next()
  }

  // Viewer cookie passes the viewer-allowed paths only.
  if (isViewerPath(pathname) && VIEWER_SECRET) {
    const viewerCookie = request.cookies.get('lila_viewer')
    const payload = await verifyViewerCookie(viewerCookie?.value, VIEWER_SECRET)
    if (payload) return NextResponse.next()
  }

  return NextResponse.redirect(new URL('/login', request.url))
}

export const config = {
  matcher: ['/((?!_next/static|_next/image|favicon\\.ico).*)'],
}
