import { NextResponse } from 'next/server'
import { getPool, ensureSchema } from '@/lib/db'

export const dynamic = 'force-dynamic'

// GET  /api/ceelo/chat?after=<id>  → messages in Ceelo's thread (operator + ceelo)
// POST /api/ceelo/chat  { content }  → operator sends a message to Ceelo
//
// Ceelo's reply is generated by the Ceelo loop on its next tick (chat
// handling runs every tick, separate from the 30-min cycle gate). UI
// polls this endpoint and the new ceelo-tagged message appears.

export async function GET(req: Request) {
  if (!process.env.DATABASE_URL) return NextResponse.json({ messages: [] })
  const after = parseInt(new URL(req.url).searchParams.get('after') ?? '0')
  // No real cursor → newest window, not the oldest rows. Mirrors the fix in
  // /api/chat/messages; without it the Ceelo thread freezes on old history.
  const incremental = Number.isFinite(after) && after > 0

  const pool = getPool()
  const db = await pool.connect()
  try {
    await ensureSchema(db)
    const { rows } = await db.query(
      incremental
        ? `SELECT id, sender, content,
                  (EXTRACT(EPOCH FROM created_at) * 1000)::bigint AS timestamp
           FROM chat_messages
           WHERE thread = 'ceelo'
             AND id > $1
           ORDER BY id ASC LIMIT 60`
        : `SELECT * FROM (
             SELECT id, sender, content,
                    (EXTRACT(EPOCH FROM created_at) * 1000)::bigint AS timestamp
             FROM chat_messages
             WHERE thread = 'ceelo'
             ORDER BY id DESC LIMIT 60
           ) s ORDER BY id ASC`,
      incremental ? [after] : []
    )
    return NextResponse.json({
      messages: rows.map(r => ({
        id: Number(r.id),
        sender: r.sender as string,
        content: r.content as string,
        timestamp: Number(r.timestamp),
      })),
    })
  } finally { db.release() }
}

export async function POST(req: Request) {
  if (!process.env.DATABASE_URL) return NextResponse.json({ error: 'no db' }, { status: 503 })
  const body = await req.json().catch(() => ({}))
  const content = String(body.content ?? '').trim().slice(0, 4000)
  if (!content) return NextResponse.json({ error: 'empty' }, { status: 400 })

  const pool = getPool()
  const db = await pool.connect()
  try {
    await ensureSchema(db)
    const { rows: [row] } = await db.query(
      `INSERT INTO chat_messages (sender, content, thread)
       VALUES ('user', $1, 'ceelo')
       RETURNING id, (EXTRACT(EPOCH FROM created_at) * 1000)::bigint AS timestamp`,
      [content]
    )
    return NextResponse.json({
      ok: true,
      id: Number(row.id),
      timestamp: Number(row.timestamp),
    })
  } finally { db.release() }
}
